FROM bellsoft/liberica-openjdk-debian:21 AS build
WORKDIR /app
COPY . .
RUN ./gradlew bootJar

FROM bellsoft/liberica-openjdk-debian:21
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
