spring:
    profiles:
        active: local
    jpa:
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: none
        database: mysql

springdoc:
    swagger-ui:
        groups-order: desc
        tags-sorter: alpha
        operations-sorter: method
        disable-swagger-default-url: true
        display-request-duration: true
        default-models-expand-depth: 3
        default-model-expand-depth: 3
        path: /docs
    api-docs:
        path: /api-docs
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    writer-with-default-pretty-printer: true
    model-and-view-allowed: false
    paths-to-match:
        - /**